version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - STORAGE_TYPE=redis
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=INFO
    depends_on:
      - redis
    volumes:
      - ./:/app
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
